//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleGitClient.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "18.7.0.0")]
    internal sealed partial class EnvSettings : global::System.Configuration.ApplicationSettingsBase {
        
        private static EnvSettings defaultInstance = ((EnvSettings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new EnvSettings())));
        
        public static EnvSettings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double LogWindowLeft {
            get {
                return ((double)(this["LogWindowLeft"]));
            }
            set {
                this["LogWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double LogWindowTop {
            get {
                return ((double)(this["LogWindowTop"]));
            }
            set {
                this["LogWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double LogWindowWidth {
            get {
                return ((double)(this["LogWindowWidth"]));
            }
            set {
                this["LogWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("600")]
        public double LogWindowHeight {
            get {
                return ((double)(this["LogWindowHeight"]));
            }
            set {
                this["LogWindowHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double CommitWindowLeft {
            get {
                return ((double)(this["CommitWindowLeft"]));
            }
            set {
                this["CommitWindowLeft"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("NaN")]
        public double CommitWindowTop {
            get {
                return ((double)(this["CommitWindowTop"]));
            }
            set {
                this["CommitWindowTop"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("480")]
        public double CommitWindowWidth {
            get {
                return ((double)(this["CommitWindowWidth"]));
            }
            set {
                this["CommitWindowWidth"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("800")]
        public double CommitWindowHeight {
            get {
                return ((double)(this["CommitWindowHeight"]));
            }
            set {
                this["CommitWindowHeight"] = value;
            }
        }
    }
}
